### ISSUE TITLE
AttributeError when trying to load barthez or mbarthez tokenizers

### ISSUE THREAD

**Issue by ell-hol** [moussaKam/BARThez#3]
>>> barthez_tokenizer = AutoTokenizer.from_pretrained("moussaKam/barthez")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ell-hol/Desktop/envs/transformers-torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 370, in from_pretrained
    tokenizer_class = tokenizer_class_from_name(tokenizer_class_candidate)
  File "/home/ell-hol/Desktop/envs/transformers-torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 273, in tokenizer_class_from_name
    if c.__name__ == class_name:
AttributeError: 'NoneType' object has no attribute '__name__

>>> barthez_tokenizer = AutoTokenizer.from_pretrained("moussaKam/mbarthez")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ell-hol/Desktop/envs/transformers-torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 370, in from_pretrained
    tokenizer_class = tokenizer_class_from_name(tokenizer_class_candidate)
  File "/home/ell-hol/Desktop/envs/transformers-torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 273, in tokenizer_class_from_name
    if c.__name__ == class_name:
AttributeError: 'NoneType' object has no attribute '__name__'

Transformers version: 4.3.2
Torch version: '1.7.1+cu101'

**Comment by moussaKam** [comment]
Hi @ell-hol can you try to install `sentencepiece` please.
`!pip install sentencepiece`

**Comment by ell-hol** [comment]
Installing sentencepiece did fix it. Thanks a lot !
